### ISSUE TITLE
Can not map database enum to Java enum

### ISSUE THREAD

**Issue by jadetang** [zalando-stups/java-sproc-wrapper#69]
### software version
1. sproc 3.0.0
2. postgresql driver version `42.2.14`

### Behavior
The stored procedure is defined as this
```
CREATE OR REPLACE FUNCTION get_some_data (
    IN  xx xxx
) 
RETURNS SETOF data AS
$body$
BEGIN
  RETURN QUERY SELECT id,
                      provider,
                 FROM data_type
END;
$body$
LANGUAGE plpgsql SECURITY DEFINER
COST 100;
```

The data type is defined like this
```
 CREATE TYPE solvency_data AS (
  id                            BIGINT,
  customer_number               TEXT,
  provider                     provider,
)
```
The solvency_provider is defined like this
```
CREATE TYPE provider AS ENUM (
  'A',
  'B',
  'C',
  'D'
);
```

During the test, there is an error log
```
2021-02-12 12:28:30.645 ERROR 21164 --- [           main] org.zalando.typemapper.core.TypeMapper   : Could not map property provider of class Data
```

### Analyze
The database enum type is recognized as `PGobject` in `TypeMapper`, see the screenshot below:
![image](https://user-images.githubusercontent.com/6525486/107785112-7a327000-6d4c-11eb-8d27-5a9b58012bc6.png)

So an `ObjectResultNode` is created, and this ObjectResultNode has a child node whose type is a simple node, see the screenshot below:
![image](https://user-images.githubusercontent.com/6525486/107785352-c41b5600-6d4c-11eb-885a-9225e46345b4.png)
During the mapping process later, the type mapper will use ObjectFieldMapper to map the database value to java value.
However, the `mapField` method throws an NPE, see the screen below:

![image](https://user-images.githubusercontent.com/6525486/107786174-d34ed380-6d4d-11eb-9bf5-c1d039025011.png)

The child name is `xxx_provider` but `node.getType()` returns `"xxx_data"."xxx_provider"`, so the `DbResultNode` is null.

### Possible root cause
The code works with the old postgresql driver version `9.4-1201-jdbc41`. Because in the new driver, the database enum type is treated as `Other`( type id is `1111`), however, in the old driver, the database enum type is treated as `LONGVARCHAR`. 

![image](https://user-images.githubusercontent.com/6525486/107766362-a42b6880-6d33-11eb-88cd-ccab3f056bad.png)

**Comment by vadeg** [comment]
Hi @jadetang!

Thank you for reporting. Would you be able to write integration test for your use case?
